name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Ruby ${{ matrix.ruby }} ${{ matrix.name_extra || '' }}
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '2.7'
          - '2.6'
        gemfile:
          - gemfiles/rack_1.5.gemfile
          - gemfiles/rack_1.6.gemfile
          - gemfiles/rack_2.0.gemfile
          - gemfiles/rack_2.1.gemfile
          - gemfiles/rack_2.2.gemfile
      fail-fast: false
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rake
